name = "emulator-production"
account_id = "55507bc40dc926344b5f2c45a528fac8"
workers_dev = false
compatibility_date = "2021-11-08"
main = "workers-site/index.ts"

durable_objects.bindings = [
    {name = "ETHERNET_ZONE", class_name = "EthernetZone"}
]
kv_namespaces = [
    {binding = "VARZ", id = "5b8240e4b8fc49f0a49f31451ae839fd", preview_id = "4915f488518240bc8ba86bbcdbd9f12e"}
]

[[migrations]]
tag = "v1"
new_classes = ["EthernetZone"]

[site]
bucket = "./build"
exclude = ["BasiliskII.wasm.map"]

[env.production]
routes = [
    {pattern = "emulator.bachmanarchives.net/*", zone_name = "bachmanarchives.net"},
]
durable_objects.bindings = [
    {name = "ETHERNET_ZONE", class_name = "EthernetZone"}
]
kv_namespaces = [
    {binding = "VARZ", id = "5b8240e4b8fc49f0a49f31451ae839fd"}
]
